# Generated by Django 4.2.7 on 2023-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Details',
            fields=[
                ('name', models.CharField(default='default_ERR_user', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(default='ERR_PAYMENT_ID_RZP', max_length=50, primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
